spring:
  application:
    name: coffeestore-api
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeestoredb
    username: coffeestore
    password: coffeestore
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
